services:
  - type: web
    name: cloud-backblaze
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn cloud_storage.wsgi"
    preDeploy:
      - python manage.py migrate
      - python manage.py collectstatic --noinput
